### ISSUE TITLE
The weighting coefficient

### ISSUE THREAD

**Issue by wxtyixiao** [pierre-rouanet/dtw#13]
In the code of dtw, maybe the weighting coefficient should be added. I don't know if my thought is right. Please give me some answers, thanks.

**Comment by pierre-rouanet** [comment]
Hi @wxtyixiao,

I don't really understand what you have in mind. Can you give a use example?

**Comment by wxtyixiao** [comment]
The distance between two time series is calculated by the formula: D(A, B)=(min(sum(d(c(k))*w(k))))/N, in which the w(k) is the weighting coefficient. It can be calculated by the symmetric form or asymmetric form.

> Sakoe H, Chiba S. Dynamic programming algorithm optimization for spoken word recognition[J]. IEEE Transactions on Acoustics Speech & Signal Processing, 1978, 26(1):43-49.

**Comment by pierre-rouanet** [comment]
Ok I see. I don't have time to add extra feature to DTW at the moment but I'll gladly integrate a PR with this.
