### ISSUE TITLE
can't run the MFCC + DTW example

### ISSUE THREAD

**Issue by zhangboyang** [pierre-rouanet/dtw#18]
```Traceback (most recent call last):
  File "mfcc.py", line 18, in <module>
    dist, cost, path = dtw(mfcc1.T, mfcc2.T)
TypeError: dtw() missing 1 required positional argument: 'dist'
```

maybe the example should be updated?

**Comment by pierre-rouanet** [comment]
I'll updated the example here: https://github.com/pierre-rouanet/dtw/pull/19

Can you check if everything is ok on your side before I merge it?

**Comment by zhangboyang** [comment]
Yes, the dtw() now works

**Comment by viswabhaskar** [comment]
File "C:\Users\VISWA\Desktop\Misc\record\diff.py", line 18, in <module>
    dist, cost, path = dtw(mfcc1.T, mfcc2.T)
TypeError: dtw() missing 1 required positional argument: 'dist'


i getting this error
