### ISSUE TITLE
Distance normalisation

### ISSUE THREAD

**Issue by themiurgo** [pierre-rouanet/dtw#2]
Why is distance normalised by over the sum of the shape the cost matrix (https://github.com/pierre-rouanet/dtw/blob/master/dtw.py#L38)? I couldn't find this in the [definition of DTW](https://en.wikipedia.org/wiki/Dynamic_time_warping).

**Comment by pierre-rouanet** [comment]
This is kind of arbitrary. This is just a way to penalize longer path. There exists many possible normalization. You can have a look at this for instance : http://www.cs.ucr.edu/~eamonn/DTW_myths.pdf

**Comment by themiurgo** [comment]
Great, thanks! And thanks for the nice library. :)
