### ISSUE TITLE
Example Notebook call error

### ISSUE THREAD

**Issue by apiszcz** [pierre-rouanet/dtw#20]
The following line returns 3 values not 4 as shown in the notebook

Produces an error message
dist, cost, acc, path = dtw(x, y, dist=lambda x, y: norm(x - y, ord=1))

No error
dist,cost,path=dtw.dtw(x, y, dist=lambda x, y: norm(x - y, ord=1))

**Comment by pierre-rouanet** [comment]
I'm not sure to understand. If you look here it returns 4 elements:

https://github.com/pierre-rouanet/dtw/blob/master/dtw.py#L34

Are you sure you are using the last version?

**Comment by apiszcz** [comment]
Thank you, i was using an old version. All set.
