### ISSUE TITLE
A question, not an issue (sorry for posting here)

### ISSUE THREAD

**Issue by fifthguy** [pierre-rouanet/dtw#21]
Hi!

Thanks for the library, I find it very useful.

I have one question though: How exactly is the cost calculated herein? As sum of the move values, that resulted in the minimum distance? 

Thank you again!

Best, T

**Comment by pierre-rouanet** [comment]
Hi! 

Thanks for using the library :)

>How exactly is the cost calculated herein? As sum of the move values, that resulted in the minimum distance?

Yep pretty much! (https://github.com/pierre-rouanet/dtw/blob/master/dtw.py#L27)

In this implementation, there is no additional cost for adding or removing elements. It's directly the element by element comparison of the two series.
There is also some weighting over the whole path (see https://github.com/pierre-rouanet/dtw/issues/2 for more details on this).

Those choices are kind of arbitrary, you can find many different implementations of DTW depending on the data you want to compare.

I don't really work on dtw anymore but I'll gladly integrate other implementation!

**Comment by pierre-rouanet** [comment]
Does that answer your question?

**Comment by fifthguy** [comment]
Hi

Sorry for not responding and closing the issue immediately, then I simply forgot.  Yes it helped, it clarified what I needed to know. Thank you very much.

Best, T
