### ISSUE TITLE
feature/collaboration request

### ISSUE THREAD

**Issue by matt256** [pierre-rouanet/dtw#22]
I implemented the streaming DTW algorithm presented in this paper: http://www.cs.cmu.edu/~christos/PUBLICATIONS/ICDE07-spring.pdf
If you all would be interested in incorporating this functionality into your package, I would be interested in working with you to incorporate it. Is this something that interests you, developers?

**Comment by pierre-rouanet** [comment]
Hi!

Great, yes sure I'll gladly integrate your algorithm! I only had time to quickly read your paper and it seems a really interesting approach.

You can directly open a PR with your modifications.

Cheers,

**Comment by matt256** [comment]
thank you sounds good. Just to clarify and give credit where credit is due, I am not the creator of the algorithm. I just implemented it. The algorithm is quite useful so I'd like to save others the time of trying to figure it out and give some more visibility to this body of work.  

It'll probably be a couple of weeks before I can do anything with it, but I'll do a PR when ready. Thanks a ton. Looking forward to it.

**Comment by pierre-rouanet** [comment]
Hi @matt256,

Any news from your project?

**Comment by pierre-rouanet** [comment]
I'll close the issue for the moment but feel free to re-open it you have some news!
