### ISSUE TITLE
Sound data missing

### ISSUE THREAD

**Issue by adamwuyu** [pierre-rouanet/dtw#23]
When I run "speech recognition", I get this error message:

FileNotFoundError:
[Errno 2] No such file or directory: 'sounds/wavToTag.txt'

Wheare is the wavToTag.txt?

**Comment by pierre-rouanet** [comment]
I did not include the sound files to avoid having a huge git repository. You can add your own wave file and  a simple text file to associate a wave filename with its associated tag.

**Comment by adamwuyu** [comment]
OK, can give me more info about the text file. Is it a blank text file?  Or does it already have tags inside? How can I get the tags?
Thank you for your reply.

**Comment by pierre-rouanet** [comment]
It's simply a text file with each line containing a single tag (any id you want to associate with a particular sound). The nth line is supposed to correspond to your nth sound.

All this can be changed in the examples. It's only the way I did it :)
