### ISSUE TITLE
Recommending a name change of the fastdtw() function

### ISSUE THREAD

**Issue by cmuell89** [pierre-rouanet/dtw#25]
A DTW variation called FastDTW is becoming an established technique in DTW literature, reducing the algorithm to a O(n) complexity: https://pdfs.semanticscholar.org/05a2/0cde15e172fc82f32774dd0cf4fe5827cad2.pdf

The fastdtw function name is confusing if a user is assuming that it implements the technique in the FastDTW paper. The current implementation is using the cdist() function from SciPy, which is an accelerated distance calculation function and not the same as the technique in the paper.

Perhaps accelerated_dtw() ?

**Comment by pierre-rouanet** [comment]
Thanks for letting me know! I'll make the change asap.

**Comment by cmuell89** [comment]
If you're curious to see an implementation, here is one:
https://github.com/slaypni/fastdtw
