### ISSUE TITLE
Why is there a '-1' in min(i+k,r-1) and min(j+k, c-1) in third for loop of dtw function?

### ISSUE THREAD

**Issue by DihengChen** [pierre-rouanet/dtw#27]

**Comment by DihengChen** [comment]
![image](https://user-images.githubusercontent.com/37919889/44358331-406bb000-a4e7-11e8-946e-c0986693fd36.png)

**Comment by mxsrc** [comment]
Since `r` and `c` correspond to the input's lengths, this will prevent indexing out of the array's bounds.

**Comment by DihengChen** [comment]
Thanks you for your reply!
But I am still confused. The i_k and j_k are used as index of matrix D0, and D0 is (c+1)*(r+1) matrix. So r and c will not be out of D0's bound.

**Comment by mxsrc** [comment]
While `r` and `c` won't be out of bounds, `i + k` and `j + k` might. In the last loop iteration, `i` will be `r-1`. When a `warp` different from `1`, e.g., `2`, is given, `i + k` will be `r - 1 + 2` and thus out of bounds for `D0`. The same applies for `j` of course.

**Comment by jlc-christie** [comment]
@pierre-rouanet resolved, close?
