### ISSUE TITLE
dist value for similar audios

### ISSUE THREAD

**Issue by enviz** [pierre-rouanet/dtw#36]
https://github.com/pierre-rouanet/dtw/blob/master/examples/MFCC%20%2B%20DTW.ipynb
(Under comparing them using DTW , In [4])
This is not really an issue,but a doubt rather.

I am doing a speech project in which I'm comparing the similarity between audios. Basically I have a bunch of phoneme recordings from the same voice. Some of them sound similar and some of them don't. So I am using this dist measure to quantify that similarity. And based on what i've observed so far with the samples I have,a dist value of anything less than 180 is holding true for similar sounding phoneme recordings and greater than 180 for the dissimilar ones.

Can I use this condition to compare the similarities? Please let me know. Thanks in advance.

**Comment by pierre-rouanet** [comment]
Hi @enviz!

Yes indeed it should work. 
The tricky part is to find a threshold that match for your case. It depends on lots of parameters and it's usually task dependent. It's usually found empirically. I guess that's how you found 180 in your case.
