### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by KongfeiH** [pierre-rouanet/dtw#37]
File "D:\Anaconda3\lib\site-packages\dtw\dtw.py", line 29, in dtw
    D0 = zeros((r + 1, c + 1))

**Comment by pierre-rouanet** [comment]
Hi @KongfeiH,

My guess is that ```r``` and/or ```c``` are just big numbers and that you don't have enough memory to fit the entire distance matrix in RAM. DTW is ```O(n^2)``` in memory.

I guess we could think of version that do not compute all the matrix at once.

**Comment by KongfeiH** [comment]
thanks。



发自我的小米手机
在 Pierre Rouanet <notifications@github.com>，2019年6月3日 下午5:32写道：

Hi @KongfeiH<https://github.com/KongfeiH>,

My guess is that r and/or c are just big numbers and that you don't have enough memory to fit the entire distance matrix in RAM. DTW is O(n^2) in memory.

I guess we could think of version that do not compute all the matrix at once.
