### ISSUE TITLE
Speech Recognition example

### ISSUE THREAD

**Issue by alexvks22** [pierre-rouanet/dtw#39]
In your example with leave out p cross validation, can you suggest another way of splitting train and test matrices? It gives me some error with find function. I searched but i didnt find the corresponding library. 
Thank you in advance

**Comment by pierre-rouanet** [comment]
Hi @alexvks22,

I guess you could use https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html.
The find function was most likely import by the deprecated ```%pylab inline```. Do not hesitate to update the example if you find a better version!

**Comment by alexvks22** [comment]
Thank you very much! I did try to with this function but the result of recognition rate was different, so i guessed that something went wrong. I’ll try again!

**Comment by pierre-rouanet** [comment]
I'll close the issue, feel free to re-open it if needed.
