### ISSUE TITLE
generate train and test report issue.

### ISSUE THREAD

**Issue by bradning** [pierre-rouanet/dtw#40]
what does function find come from?

it reports error in speech-recognition when train and test data split.
NameError: name 'find' is not defined

**Comment by pierre-rouanet** [comment]
See https://github.com/pierre-rouanet/dtw/issues/39.

Do not hesitate to submit a PR with a fix.

**Comment by bradning** [comment]
Thanks.
I wrote a find function myself, could you check with it?

```
# the function will return a  list with all index of lables matched para 's'
def find( s ):
     match_result = []
     for i in range(len(labels)):
         if labels[i] == s:
             match_result.append(i)
 
     return match_result
```

after that, I made a replacement below.
from 
all = find(labels == s)
to my function
all = find(s)

I can get recognition rate 75.0% and 66.7% in two seperate run.

**Comment by pierre-rouanet** [comment]
I've updated the  example to use the speech commands TensorFlow dataset and remove the use of this find function.
