### ISSUE TITLE
inconsistency issue btw version 1.33 and v1.4.0

### ISSUE THREAD

**Issue by mydatech001** [pierre-rouanet/dtw#44]
we apply the same dtw function to the same data but the return the d value is different. in v1.3.3, the value is around 1.3 but in v1.4.0, the d value become nearly 15....

dtw(a, b, dist=euclidean_norm)

any advise why so and which version give the right answer? many thanks

**Comment by pierre-rouanet** [comment]
This is due to a normalisation removal. See https://github.com/pierre-rouanet/dtw/issues/42
