### ISSUE TITLE
MFCC + DTW example has dissapeared

### ISSUE THREAD

**Issue by emilio-molina** [pierre-rouanet/dtw#5]
Hi, thanks for your examples. Unfortunately, http://nbviewer.ipython.org/github/pierre-rouanet/dtw/blob/master/MFCC%20%2B%20DTW.ipynb is not found.

**Comment by pierre-rouanet** [comment]
You can find it here: https://github.com/pierre-rouanet/dtw/blob/master/MFCC%20%2B%20DTW.ipynb
