### ISSUE TITLE
ImportError: cannot import name dtw

### ISSUE THREAD

**Issue by kaygudo** [pierre-rouanet/dtw#6]
Hello,
I am getting an error while importing "from dtw import dtw"  which says:
"ImportError: cannot import name dtw", it would be kind if you can provide any suggestion to solve it.

**Comment by pierre-rouanet** [comment]
Hi,

You'll have to give more info. This should work.

How did you install the package? How do you try to import, etc...

**Comment by mynameisvinn** [comment]
try python -m pip install dtw, that worked for me

**Comment by pierre-rouanet** [comment]
Fixed in https://github.com/pierre-rouanet/dtw/commit/fd625b23f63fe8da56354478404b2a8627e63c0b.
